#!/bin/bash

pid_file="/var/run/sunshine.pid"

start() {
	echo -n "Starting sunshine (desktop streaming) service: "
	export DISPLAY=:0.0
	start-stop-daemon -S -b -q -m -p ${pid_file} -x /usr/bin/sunshine > /dev/null
	RETVAL=$?
		
	echo "done"
	return $RETVAL
}

stop() {
	echo -n "Stopping sunshine (desktop streaming) service: "

	#start-stop-daemon -K -q -p ${pid_file}
	# use this to kill the whole process tree
	pid=`cat ${pid_file}`
	pkill -P ${pid}
	
	RETVAL=$?
	
	echo "done"
	return $RETVAL
}

status() {
    if start-stop-daemon --status -q -p ${pid_file}
    then
	echo "started"
    else
	echo "stopped"
    fi
}

case "$1" in
	start)
			start
			;;
	stop)
			stop
			;;
	status)
			status
			;;
	*)
			echo "Usage: $0 {start|stop}"
			exit 1
esac

exit $?
